openapi: 3.0.0
info:
  description: REST API
  title:  API
  version: '1.0'
  contact:
    email: email@emil.com
servers:
  - url: /v1/
paths:
  '/users':
    get:
      parameters:
        - in: query
          name: email
          schema:
            type: string
            required: false
      responses:
        200:
          description: Request has been processed
        500:
          description: Internal server error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
              example:
                { "name": "John Doe", "email": "john.doe@email.com" }
      responses:
        204:
          description: Request has been processed
        400:
          description: Provided reqeust is not valid
        500:
          description: Internal server error
  '/users/{userId}':
    get:
      parameters:
        - in: path
          name: userId
          schema:
            type: string
            required: true
      responses:
        204:
          description: Request has been processed
        400:
          description: Provided reqeust is not valid
        404:
          description: No found resources for provided request
        500:
          description: Internal server error
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
